#!/usr/bin/env bash
# Configure the server to listen on port 80 for all active IPv4 addresses

sudo sed -i 's/8080/80/' /etc/nginx/sites-enabled/default
sudo systemctl restart nginx
echo -n "" | sudo dd status=none of=/run/nginx.pid
